//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class PruebaTecnicaEntities : DbContext
    {
        public PruebaTecnicaEntities()
            : base("name=PruebaTecnicaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ventas> ventas { get; set; }
    
        [DbFunction("PruebaTecnicaEntities", "getTopVentas")]
        public virtual IQueryable<getTopVentas_Result> getTopVentas()
        {
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<getTopVentas_Result>("[PruebaTecnicaEntities].[getTopVentas]()");
        }
    }
}
